### ISSUE TITLE
In day/year inputs, placeholder is not working.

### ISSUE THREAD

**Issue by rohith28** [Software-Engineering-S18-Group2/jscalc#8]
Currently in month/day/year inputs, there is no placeholder to indicate the value should be day or year.
See example on screenshot:
![image](https://user-images.githubusercontent.com/18727359/39399203-c757d116-4ae7-11e8-848f-c36b7e077b54.png)

**Comment by CHico-Lee** [comment]
In case of the user removed all the value from the field, or default values are set as empty. It would be clear to have the placeholder to show that is a month or day field.

**Comment by rohith28** [comment]
@CHico-Lee @farhanak @mounika439 

I think this is now fixed... Can I close the issue?

**Comment by mounika439** [comment]
Yes, this issue is fixed.
